feat: implement seed word phrase counter
status-im/nim-status-client pull request #1101
Opened 2020-10-03 14:06 UTC by hydr063n

fixes: https://github.com/status-im/nim-status-client/issues/1078

- If the count matches the required amount a tick will be included next the count
- The format is "✓ 12 words"
- This commit also fixes the text color when in dark in the wallet add new account modal
- This feature is added on both login and wallet add account with wallet seed modal

![](https://i.imgur.com/cYzlRoF.png)
![](https://i.imgur.com/BLFuoR7.png)
![](https://i.imgur.com/Wb5G8VF.png)
![](https://i.imgur.com/eXSBxo6.png)

2020-10-03 14:14 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 922cd7bd | [#1](https://ci.status.im/job/nim-status-client/job/macos/job/PR-1101/1/) | 2020-10-03 14:14:36 | ~7 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-201003-140650-922cd7-pr.dmg) |

2020-10-05 12:53 UTC, richard-ramos commented on ui/imports/Utils.qml
> +        return getTick(wordCount) + wordCount.toString() + " words";
```suggestion
        return qsTr("%1%2 words").arg(getTick(wordCount)).arg(wordCount.toString());
```

2020-10-05 12:54 UTC, richard-ramos requested changes
Very cool! only a small change requested for i18n and we're good to go! thank you, @hydr063n! :)

2020-10-05 13:00 UTC, hydr063n commented on ui/imports/Utils.qml
> +        return getTick(wordCount) + wordCount.toString() + " words";
Fixed! Forgot about translations!

2020-10-05 13:42 UTC, jrainville approved these changes
Nice, very cool

2020-10-05 14:52 UTC, merged