fix: stop crash by showing error message
status-im/nim-status-client pull request #1431
Opened 2020-11-30 21:38 UTC by hydr063n

fix https://github.com/status-im/nim-status-client/issues/898

The segmentation fault occured because the RPC response returned json with an error message as opposed to the usual data required to update the chat. Since the section of the code didn't handle this error message it caused the app to crash. I've handled this error to show an error alert box by emitting a `sendMessageFailed` event

![block_user_crash](https://user-images.githubusercontent.com/58890963/100668625-e7954e00-3364-11eb-8425-a06441920a8a.gif)

2020-11-30 21:48 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 2dd74246 | [#1](https://ci.status.im/job/nim-status-client/job/macos/job/PR-1431/1/) | 2020-11-30 21:48:25 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-201130-213908-2dd742-pr.dmg) |

2020-11-30 21:49 UTC, emizzle requested changes
Great work @hydr063n! Instead of showing an error message, would you be able to instead make the chat input read only when the user is blocked. It would also be nice to show "User is blocked." in the chat input so that the user is aware of why they cannot send a message.

2020-12-01 18:40 UTC, merged

2020-12-01 20:20 UTC, iurimatias commented
@hydr063n could you address these in a different PR please

2020-12-02 00:27 UTC, hydr063n commented
hey all, thanks! Yeah I can make the change to check if the user is blocked! I will submit this a new PR!