chore: bump nimqml and dotherside
status-im/nim-status-client pull request #1565
Opened 2020-12-21 22:44 UTC by emizzle

Both nimqml and dotherside now point to their respective master branches. Previously, the commits were pointing to branches or detached HEADs.

2020-12-21 22:44 UTC, richard-ramos approved these changes

2020-12-21 22:52 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 23ac056c | [#1](https://ci.status.im/job/nim-status-client/job/macos/job/PR-1565/1/) | 2020-12-21 22:52:31 | ~8 min | `macos` | [:page_facing_up:`log`](https://ci.status.im/job/nim-status-client/job/macos/job/PR-1565/1/consoleText) |

2020-12-22 14:51 UTC, jrainville requested changes
Marking as requesting changes because the build fails. 
```
22:52:30  /Users/jenkins/workspace/nim-status-client_macos_PR-1565/src/nim_status_client.nim(69, 30) Error: undeclared identifier: 'newQNetworkAccessManagerFactory'
22:52:30  make: *** [nim_status_client] Error 1
```

2020-12-22 15:31 UTC, jrainville approved these changes

2020-12-22 21:08 UTC, merged